services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    contao.command.member_create:
        class: AVL\MemberConsole\Command\MemberCreateCommand
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@security.password_hasher_factory'

    contao.command.member_list:
        class: AVL\MemberConsole\Command\MemberListCommand
        arguments:
            - '@database_connection'

    contao.command.member_password:
        class: AVL\MemberConsole\Command\MemberPasswordCommand
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@security.password_hasher_factory'

    contao.command.member_delete:
        class: AVL\MemberConsole\Command\MemberDeleteCommand
        arguments:
            - '@contao.framework'
            - '@database_connection'